import React from 'react';
import { Link } from 'react-router-dom';
import { Card } from '../components/ui';
import Footer from '../components/Footer';

const TermsOfService: React.FC = () => {
  return (
    <div className="min-h-screen bg-surface-50">
      <div className="max-w-4xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
        <div className="mb-8">
          <Link to="/" className="text-primary-600 hover:text-primary-700 flex items-center mb-4">
            <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Home
          </Link>
          <h1 className="text-3xl font-bold text-surface-900">Terms of Service</h1>
          <p className="text-surface-600 mt-2">Last updated: {new Date().toLocaleDateString()}</p>
        </div>

        <Card className="p-8 mb-8">
          <div className="prose max-w-none">
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 mb-6">
              <div className="flex">
                <svg className="w-5 h-5 text-yellow-400 mr-2 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
                <div>
                  <h3 className="text-yellow-800 font-medium">Development Notice</h3>
                  <p className="text-yellow-700 text-sm mt-1">
                    RT1M is currently in active development and testing phase. This application is provided for 
                    testing purposes only and should not be used for actual financial planning or decision-making.
                  </p>
                </div>
              </div>
            </div>

            <h2 className="text-xl font-semibold text-surface-900 mb-4">1. Acceptance of Terms</h2>
            <p className="text-surface-700 mb-6">
              By accessing and using RT1M ("the Application"), you accept and agree to be bound by the terms 
              and provision of this agreement. This is a testing application under development, and your use 
              constitutes participation in our testing program.
            </p>

            <h2 className="text-xl font-semibold text-surface-900 mb-4">2. Development Status</h2>
            <p className="text-surface-700 mb-6">
              RT1M is currently in active development. Features may be incomplete, contain bugs, or change 
              without notice. The application is provided "as is" for testing purposes only. We make no 
              warranties about the completeness, reliability, or accuracy of the information provided.
            </p>

            <h2 className="text-xl font-semibold text-surface-900 mb-4">3. Testing Data</h2>
            <p className="text-surface-700 mb-6">
              All data entered into this application during the testing phase may be subject to deletion, 
              modification, or loss without notice. Do not enter sensitive, real, or personally identifiable 
              financial information. Use test data only.
            </p>

            <h2 className="text-xl font-semibold text-surface-900 mb-4">4. No Financial Advice</h2>
            <p className="text-surface-700 mb-6">
              This application is for testing purposes only and does not provide financial advice. Any 
              calculations, suggestions, or recommendations generated by the application should not be 
              considered as professional financial guidance and should not influence real financial decisions.
            </p>

            <h2 className="text-xl font-semibold text-surface-900 mb-4">5. User Responsibilities</h2>
            <p className="text-surface-700 mb-6">
              As a tester, you agree to:
            </p>
            <ul className="list-disc list-inside text-surface-700 mb-6 space-y-2">
              <li>Use only test data, not real personal or financial information</li>
              <li>Report bugs and issues encountered during testing</li>
              <li>Not attempt to exploit or damage the application</li>
              <li>Understand that this is a development environment</li>
            </ul>

            <h2 className="text-xl font-semibold text-surface-900 mb-4">6. Data Security</h2>
            <p className="text-surface-700 mb-6">
              While we implement reasonable security measures, this is a testing environment and should not 
              be considered secure for real data. We are not responsible for any data loss, breach, or 
              unauthorized access during the testing phase.
            </p>

            <h2 className="text-xl font-semibold text-surface-900 mb-4">7. Limitation of Liability</h2>
            <p className="text-surface-700 mb-6">
              RT1M and its developers shall not be liable for any direct, indirect, incidental, special, 
              consequential, or punitive damages resulting from your use of this testing application.
            </p>

            <h2 className="text-xl font-semibold text-surface-900 mb-4">8. Changes to Terms</h2>
            <p className="text-surface-700 mb-6">
              We reserve the right to modify these terms at any time during the development process. 
              Continued use of the application constitutes acceptance of any changes.
            </p>

            <h2 className="text-xl font-semibold text-surface-900 mb-4">9. Contact Information</h2>
            <p className="text-surface-700 mb-6">
              For questions about these Terms of Service or to report issues during testing, please contact 
              us at <a href="mailto:support@rt1m.app" className="text-primary-600 hover:text-primary-700">support@rt1m.app</a>.
            </p>

            <div className="border-t border-surface-200 pt-6 mt-8">
              <p className="text-sm text-surface-500">
                These terms are specific to the development and testing phase of RT1M. They will be updated 
                before any public release of the application.
              </p>
            </div>
          </div>
        </Card>
      </div>
      <Footer />
    </div>
  );
};

export default TermsOfService; 